name: Automatic pull request approval

on:
  pull_request_target:
    types:
      - opened
    branches: [master]
    
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: AndrewMusgrave/automatic-pull-request-review@0.0.2
        if: github.actor == 'MoralesJonathan'
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          event: APPROVE
          body: 'Approved with GH Action'
          
